version: '3.8'

services:
  api:
    container_name: desafio-backend-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3333:3333
    volumes:
      - ./src:/home/app/src
      - ./package.json:/home/app/package.json
    depends_on:
      - postgres

  postgresql:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: desafio-backend
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
