FROM node:14-alpine as builder

WORKDIR /home/app

COPY . ./

RUN yarn && yarn cache clean

RUN yarn tsc

FROM node:14-alpine

WORKDIR /home/app

COPY ./package.json ./
COPY ./.env.production ./.env

RUN yarn --production && yarn cache clean

COPY --from=builder ./home/app/dist ./dist

EXPOSE 3333

CMD ["yarn", "start"]
